apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: aleksejs-pod
  name: aleksejs-pod-manifest
spec:
  containers:
  - image: nginx
    name: aleksejs-pod-frommanifest
    resources: {}
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: aleksejs-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: aleksejs-volume
      hostPath:
        path: /home/martins
status: {}
