apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: aleksejs-test
  name: redis-aleksejs
spec:
  containers:
  - image: redis
    name: aleksejs-test-redis
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
