apiVersion: apps/v1
kind: Deployment
metadata:
  name: aleksejs-nginx-depl
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-depl
  template:
    metadata:
      labels:
        app: nginx-depl
    spec:
      containers:
      - name: aleksejs-nginx-depl
        image: nginx
        ports:
        - containerPort: 80
